name: Sync to Public Repository
on:
  push:
    branches:
      - main

jobs:
  sync-to-public:
    if: contains(github.event.head_commit.message, 'public push')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Push to public repository
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          echo "Setting up remote repository..."
          git remote set-url origin "https://${{ github.actor }}:${GITHUB_TOKEN}@github.com/vali-ray/infinite_games.git"
          echo "Pushing to pre-prod branch..."
          git push origin main:pre-prod --force
          
      - name: Send success message to Telegram
        if: success()
        run: |
          BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          CHAT_ID="${{ secrets.CHAT_ID }}"
          MESSAGE="✅ Sync public repo complete"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" -d text="${MESSAGE}"
          
      - name: Send failure message to Telegram
        if: failure()
        run: |
          BOT_TOKEN="${{ secrets.BOT_TOKEN }}"
          CHAT_ID="${{ secrets.CHAT_ID }}"
          MESSAGE="❌ Sync public repo fail"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
          -d chat_id="${CHAT_ID}" -d text="${MESSAGE}"
