name: Update CI cache

on:
  push:
    branches:
      - "develop"
      - "stage"
      - "main"

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Python minor version
        run: |
          VERSION=${{ steps.setup-python.outputs.python-version }}
          VERSION_FORMATTED=$(echo $VERSION | cut -d '.' -f 1,2)

          echo "python-version=${{ steps.setup-python.outputs.python-version }}"
          echo "python_version_formatted=$VERSION_FORMATTED" >> $GITHUB_ENV
          echo "Formatted Python minor version: $VERSION_FORMATTED"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            /opt/hostedtoolcache/Python/${{ steps.setup-python.outputs.python-version }}/x64/lib/python${{ env.python_version_formatted }}/site-packages
            /opt/hostedtoolcache/Python/${{ steps.setup-python.outputs.python-version }}/x64/bin
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements*.txt') }}

      - name: Install packages
        run: pip install -r requirements_dev.txt
